[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scopexr"
version = "1.3.4"


description = "Single-image Characterization Of PErformance in X-Ray systems"
authors = [
  { name = "Jacopo Altieri", email = "jacopo.altieri@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "PyQt6",
    "PyYAML",
    "scikit-image",
    "opencv-python",
    "pydicom"
]

[project.urls]
Homepage = "https://github.com/jacopoaltieri/scope-xr"
Documentation = "https://scope-xr.readthedocs.io/"
Repository = "https://github.com/jacopoaltieri/scope-xr"
Issues = "https://github.com/jacopoaltieri/scope-xr/issues"
Changelog = "https://github.com/jacopoaltieri/scope-xr/blob/main/CHANGELOG.md"
Contributing = "https://github.com/jacopoaltieri/scope-xr/blob/main/CONTRIBUTING.md"

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
]

test = [
    "pytest",
    "pytest-cov",
]

dev = [
    "ruff"
]

all = [
    "scopexr[docs,test,dev]"
]

[project.scripts]
scopexr-gui = "scopexr.gui:main"
scopexr-fs = "scopexr.fs_main:main"
scopexr-psf = "scopexr.psf_main:main"


[tool.setuptools.package-data]
scopexr = ["*.png"]

[tool.semantic_release]
version_variable = "pyproject.toml:version"
version_toml = ["pyproject.toml:project.version"]
major_on_zero = false
branch = "main"

[tool.semantic_release.changelog]
exclude_commit_types = ["chore", "test"]

[tool.semantic_release.publish]
dist_dir = "dist"
upload_to_vcs_release = true